### ISSUE TITLE
Subclassing 

### ISSUE THREAD

**Issue by hujosh** [pybee/cricket#47]
The tree structure of cricket is this

directory/file/classes/testmethods

is it possible to have a level between classes and testmethods, so subclasses?

**Comment by freakboy3742** [comment]
Depends on the type of test suite you're running.

If you're using a unittest suite, or a Django 1.6+ test runner, the tree will reflect the structure discovered by unittest. If you have directories and subdirectories, these will be reflected in the Cricket tree. Whatever structure unittest discovers, Cricket will reflect.

This isn't possible on a Django < 1.6 test runner - but that's a limitation of the Django test runner itself - it collapses the test tree internally.

If you want to follow up on any of this, please head over to the [BeeWare-users](https://groups.google.com/forum/#!pendingmsg/beeware-users) mailing list; this ticket tracker is for bugs, rather than handling support queries.
